function footer(){
    var html = "";
    html += '<footer class="bg-dark pt-5 lisk-footer-font">';
    html += '<div class="container">';
    html += '<div class="row pl-5 pr-5 pb-5">';
    html += '<div class="col-sm-12 pt-5 pb-3 lisk-footer-gray">';
    html += '<img class="pb-3" alt="Lisk Japan" src="img/lisk_japan_logo-white.svg" width="180">';
    html += '<br>Lisk Japan was started with the aim of spreading the blockchain application platform Lisk aiming at "Easier blockchain construction".';
    html += '<br>Consists of people with experience as designers, frontend engineers, backend engineers, network engineers, blockchain engineers and marketing directors.';
    html += '</div>';
    html += '<div class="col-sm-4 pt-3 lisk-footer-gray">';
    html += '<div class="col-md-12 h5 pl-0 pt-5 font-weight-bold lisk-footer-white">Lisk Official</div>';
    html += 'Your gateway into Blockchain';
    html += '<br><a class="btn btn-secondary mt-3" href="https://lisk.io/" role="button">Lean more <i class="fas fa-external-link-alt"></i></a>';
    html += '</div>';
    html += '<div class="col-sm-4 pt-3 lisk-footer-gray">';
    html += '<div class="col-md-12 h5 pl-0 pt-5 font-weight-bold lisk-footer-white">Development</div>';
    html += 'Lisk Core, SDK, Wallet on GitHub';
    html += '<br><a class="btn btn-secondary mt-3" href="https://github.com/LiskHQ" role="button">Lean more <i class="fas fa-external-link-alt"></i></a>';
    html += '</div>';
    html += '<div class="col-sm-4 pt-3 lisk-footer-gray">';
    html += '<div class="col-md-12 h5 pl-0 pt-5 font-weight-bold lisk-footer-white">Wallet</div>';
    html += 'for iOS, Android, Windows, Linux';
    html += '<br><a class="btn btn-secondary mt-3" href="https://lisk.io/wallet" role="button">Download Wallet <i class="fas fa-external-link-alt"></i></a>';
    html += '</div>';
    html += '<div class="col-sm-4 pt-3 lisk-footer-gray">';
    html += '<div class="col-md-12 h5 pl-0 pt-5 font-weight-bold lisk-footer-white">Community</div>';
    html += 'Join on Lisk Official Discord';
    html += '<br><a class="btn btn-secondary mt-3" href="https://discordapp.com/invite/7EKWJ7b" role="button">Join Discord <i class="fas fa-external-link-alt"></i></a>';
    html += '</div>';
    html += '<div class="col-sm-4 pt-3 lisk-footer-gray">';
    html += '<div class="col-md-12 h5 pl-0 pt-5 font-weight-bold lisk-footer-white">Roadmap</div>';
    html += 'Road to Blockchain Interoperability';
    html += '<br><a class="btn btn-secondary mt-3" href="https://lisk.io/roadmap" role="button">Lean more <i class="fas fa-external-link-alt"></i></a>';
    html += '</div>';
    html += '<div class="col-sm-4 pt-3 pb-5 mb-2 lisk-footer-gray">';
    html += '<div class="col-md-12 h5 pl-0 pt-5 font-weight-bold lisk-footer-white">Document</div>';
    html += 'Building a blockchain application';
    html += '<br><a class="btn btn-secondary mt-3" href="https://lisk.io/documentation/lisk-sdk" role="button">Lean more <i class="fas fa-external-link-alt"></i></a>';
    html += '</div>';
    html += '</div>';
    html += '</div>';
    html += '</footer>';
    html += '<div class="pt-5 pb-4 lisk-footer-gray lisk-footer-font" style="background-color: #333333;">';
    html += '<p class="text-center">&copy;2020 Lisk Japan All Rights Reserved.</p>';
    html += '</div>';
    document.write(html);
    }