function poc_list(){
    var html = "";
    html += '<div class="lisk-news mb-2 lisk-news-center"><div class="lisk-poc-list-1">IoT+Blockchain</div><span class="text-gray pl-2 pr-2 font-weight-normal lisk-poc-list-2">Lisk.Bike</span><a href="poc-liskbike.html" class="text-white">Read <i class="fas fa-external-link-alt"></i></a></div>';
    html += '<div class="lisk-news mb-2 lisk-news-center"><div class="lisk-poc-list-1">Archive+Blockchain</div><span class="text-gray-dark pl-2 pr-2 font-weight-normal lisk-poc-list-2">Chronicler</span><a href="poc-Chronicler.html" class="text-white">Read <i class="fas fa-external-link-alt"></i></a></div>';
    html += '<div class="lisk-news mb-2 lisk-news-center"><div class="lisk-poc-list-1">Event+Blockchain</div><span class="text-gray-dark pl-2 pr-2 font-weight-normal lisk-poc-list-2">Lisk Inviter</span><a href="poc-liskinviter.html" class="text-white">Read <i class="fas fa-external-link-alt"></i></a></div>';
    html += '<div class="lisk-news mb-2 lisk-news-center"><div class="lisk-poc-list-1 text-green-dark">Exchange+Blockchain</div><span class="text-gray-dark pl-2 pr-2 font-weight-normal lisk-poc-list-2">Lisk DEX</span><a href="#" class="text-gray-dark">Soon</a></div>';
    html += '<div class="lisk-news mb-2 lisk-news-center"><div class="lisk-poc-list-1 text-green-dark">Quiz+Blockchain</div><span class="text-gray-dark pl-2 pr-2 font-weight-normal lisk-poc-list-2">LQuiz</span><a href="#" class="text-gray-dark">Soon</a></div>';
    html += '<div class="lisk-news mb-2 lisk-news-center"><div class="lisk-poc-list-1 text-green-dark">API+Blockchain</div><span class="text-gray-dark pl-2 pr-2 font-weight-normal lisk-poc-list-2">Moracle</span><a href="#" class="text-gray-dark">Soon</a></div>';
    html += '<div class="lisk-news mb-2 lisk-news-center"><div class="lisk-poc-list-1 text-green-dark">Crowdfunding+Blockchain</div><span class="text-gray-dark pl-2 pr-2 font-weight-normal lisk-poc-list-2">bdonor</span><a href="#" class="text-gray-dark">Soon</a></div>';
    html += '<div class="lisk-news mb-2 lisk-news-center"><div class="lisk-poc-list-1 text-green-dark">Database+Blockchain</div><span class="text-gray-dark pl-2 pr-2 font-weight-normal lisk-poc-list-2">Global Data Chain</span><a href="#" class="text-gray-dark">Soon</a></div>';
    html += '<div class="lisk-news mb-2 lisk-news-center"><div class="lisk-poc-list-1 text-green-dark">Gamble+Blockchain</div><span class="text-gray-dark pl-2 pr-2 font-weight-normal lisk-poc-list-2">Lisk Roulette</span><a href="#" class="text-gray-dark">Soon</a></div>';
document.write(html);
}