function sdk_demo(){
    var html = "";
    html += '<!-------Section 3 Start-------><div class="row pl-3 pr-3">';
    html += '<div class="col-md-12 pt-5 mt-5">';
    html += '<div class="col-md-12 h4 p-0 text-dark font-weight-bold">Lisk SDKで開発されたアプリケーションデモサイト</div><hr>';
    html += 'Liskコミュニティで開発されたSDKを使用した概念実証（PoC）ブロックチェーンアプリケーション。<br><br><br>';
    html += '</div>';
    html += '<div class="col-sm-4 pb-5 text-center">';
    html += '<img src="img/03_roulette_0.png" width="48px"><br>';
    html += '<div class="lisk-demo text-dark">Lisk Roulette</div><br>';
    html += '分散型ルーレットゲーム<br>';
    html += '<a class="btn btn-bg-gray mt-3" href="https://roulette.delegate.moosty.com/" role="button">DEMO <i class="fas fa-external-link-alt"></i></a>';
    html += '</div>';
    html += '';
    html += '<div class="col-sm-4 pb-5 text-center">';
    html += '<img src="img/04_globaldatachain_0.png" width="48px"><br>';
    html += '<div class="lisk-demo text-dark">Lisk Global Data Chain</div><br>';
    html += '分散型データベース<br>';
    html += '<a class="btn btn-bg-gray mt-3" href="http://globaldatachain.korben3.com/" role="button">DEMO <i class="fas fa-external-link-alt"></i></a>';
    html += '</div>';
    html += '';
    html += '<div class="col-sm-4 pb-5 text-center">';
    html += '<img src="img/12_chronicler_0.png" width="48px"><br>';
    html += '<div class="lisk-demo text-dark">Chronicler</div><br>';
    html += '分散型Webアーカイブ<br>';
    html += '<a class="btn btn-bg-gray mt-3" href="https://www.chronicler.cc/" role="button">DEMO <i class="fas fa-external-link-alt"></i></a>';
    html += '</div>';
    html += '<!-------Section 3 End-------></div>';
    html += '';
    html += '<!-------Section 3 Start-------><div class="row text-center pl-3 pr-3">';
    html += '<div class="col-sm-4 pb-5 text-center">';
    html += '<img src="img/01_inviter_0.png" width="48px"><br>';
    html += '<div class="lisk-demo text-dark">Lisk Inviter</div><br>';
    html += '分散型イベント管理<br>';
    html += '<a class="btn btn-bg-gray mt-3" href="http://lisk-inviter.sidechainsolutions.io/" role="button">DEMO <i class="fas fa-external-link-alt"></i></a>';
    html += '</div>';
    html += '';
    html += '<div class="col-sm-4 pb-5 text-center">';
    html += '<img src="img/20_lquiz_0.png" width="48px"><br>';
    html += '<div class="lisk-demo text-dark">LQuiz</div><br>';
    html += '分散型クイズゲーム<br>';
    html += '<a class="btn btn-bg-gray mt-3" href="https://lquiz.ysdev.work/open-question" role="button">DEMO <i class="fas fa-external-link-alt"></i></a>';
    html += '</div>';
    html += '';
    html += '<div class="col-sm-4">';
    html += '';
    html += '</div>';
    html += '<!-------Section 3 End-------></div>';
document.write(html);
}